### ISSUE TITLE
オーバーレイタイマー

### ISSUE THREAD

**Issue by chrootRISCassembler** [chrootRISCassembler/CapsLock#14]
Steamの実績のごとく　オーバーレイ表示されるタイマーを実装
お客さんが長時間ゲームをプレイすることを抑止する

**Comment by domasyake** [comment]
終了検知できないので10分警告が出る前にゲームを閉じて放置するとゲームが起動してなくても警告が出る。終了検知できるようになったらそこにpreset()を記述するだけで解決
